#!/usr/bin/env python3
"""Ajoute les 9 pages vague 13 au générateur build_site.py"""
import sys

NEW_PAGES = '''
    dict(
        file="automatisation-avocat.html",
        title="Automatisation cabinet d'avocat : relances, CR, rendez-vous : le cabinet qui encaisse",
        meta="Relances clients, comptes-rendus, rendez-vous, suivi des dossiers : comment un cabinet d'avocats automatise son administratif. Exemples concrets.",
        h1="Avocat : <em>le temps de plaider, pas de relancer.</em>",
        sub="Chaque dossier = des relances, des CR, des rendez-vous, des factures. Le cabinet facture ses heures : sauf qu'elles partent en administration. Voici ce qu'on automatise.",
        sections=[
            section("Le quotidien du cabinet", "Les frustrations qui mangent les heures facturables",
                pains([
                    ("Les relances clients", "Pièces, honoraires, rendez-vous", "Des heures perdues", "Relance polie et automatique en 3 paliers"),
                    ("Les comptes-rendus", "Notes d'entretien, audiences", "Des nuits de rédaction", "CR structuré généré puis validé"),
                    ("Le suivi des dossiers", "Où en est chaque dossier ?", "Des tableaux à refaire", "Suivi automatique + alertes d'échéance"),
                ])),
            section("Les 8 tâches à automatiser", "Du rendez-vous au dossier clôturé",
                pains([
                    ("Prise de RDV + rappels", "Consultations, audiences", "Des no-show", "Créneaux proposés + rappel J-1"),
                    ("Relance des pièces clients", "Documents manquants", "Des dossiers bloqués", "Relance polie et automatique"),
                    ("Comptes-rendus d'entretien", "Notes de consultation", "Des heures de rédaction", "CR structuré généré puis validé"),
                    ("Relance des honoraires", "Factures, provisions", "Trésorerie tendue", "Relance en 3 paliers"),
                    ("Suivi des échéances", "Audiences, délais, recours", "Des oublis graves", "Alertes automatiques avant chaque échéance"),
                    ("Le standard / questions", "Honoraires, rendez-vous, dossiers", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Les avis Google", "La réputation locale", "Des clients satisfaits silencieux", "Demande d'avis après la clôture"),
                    ("Le tri des emails", "Clients, tribunaux, oppositions", "Des heures de tri", "Tri automatique + priorisation"),
                ])),
            section("Votre crainte, honnêtement", "« Le droit, c'est de la relation de confiance, pas des robots. »",
                prose("<p>Et c'est exactement le principe : <strong>le conseil et la défense restent 100 % humains</strong>. L'automatisation s'occupe des relances, CR, échéances et factures : le client voit un cabinet organisé qui ne laisse rien passer. C'est votre meilleure réputation.</p>")),
        ],
        faq=[
            ("Le secret professionnel est-il respecté ?", "Oui : les données restent dans vos outils, l'automatisation ne les sort jamais de votre système. Vous validez chaque envoi."),
            ("Ça marche avec mon logiciel métier ?", "Oui : on se branche sur vos outils (gestion de dossiers, facturation, agenda). Rien ne change pour votre équipe."),
            ("Par quoi commencer ?", "Les relances d'honoraires : c'est le poste qui augmente immédiatement votre trésorerie."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("hub-b2b-pro.html", "Réservoir B2B"), ("professions-liberales.html", "Professions libérales"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-coach-sportif.html",
        title="Automatisation coach sportif : séances, rappels, abonnements : le coach qui remplit ses créneaux",
        meta="Rappels de séance, créneaux, abonnements, avis : comment un coach sportif remplit son planning et fidélise. Exemples concrets.",
        h1="Coach sportif : <em>des créneaux pleins, des clients réguliers.</em>",
        sub="Chaque séance annulée est une perte sèche. Les rappels, les abonnements et les avis font la différence. Voici comment l'automatisation les rend automatiques.",
        sections=[
            section("Le quotidien du coach", "Les frustrations qui vident le planning",
                pains([
                    ("Les séances annulées", "Des no-show de dernière minute", "Des pertes sèches", "Rappel automatique + liste d'attente"),
                    ("Les clients irréguliers", "Ils viennent, puis disparaissent", "Des revenus instables", "Rappels de reprise personnalisés"),
                    ("Les avis Google", "La réputation locale", "Des clients satisfaits silencieux", "Demande d'avis après la séance"),
                ])),
            section("Les 8 tâches à automatiser", "De la première séance au client fidèle",
                pains([
                    ("Prise de RDV + rappels", "Séances, bilans", "Des no-show", "Créneaux proposés + rappel J-1"),
                    ("Liste d'attente intelligente", "Une annulation", "Un créneau vide", "Le prochain client prévenu automatiquement"),
                    ("Abonnements / packs", "Forfaits, cartes de séances", "Des revenus irréguliers", "Rappel + renouvellement automatique"),
                    ("Rappels de reprise", "Clients absents depuis 2 semaines", "Des clients perdus", "Message personnalisé de reprise"),
                    ("Demande d'avis après la séance", "Le client est motivé", "Des avis jamais écrits", "SMS post-séance → avis Google"),
                    ("Le standard / questions", "Horaires, tarifs, programmes", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Comptes-rendus de bilan", "Objectifs, progression", "Des heures de rédaction", "CR structuré généré puis validé"),
                    ("Relance des impayés", "Packs, séances", "Trésorerie tendue", "Relance polie en 3 paliers"),
                ])),
            section("Votre crainte, honnêtement", "« Le coaching, c'est de la motivation humaine. »",
                prose("<p>Et elle le reste : <strong>la séance et la motivation restent 100 % humaines</strong>. L'automatisation s'occupe des rappels, créneaux, abonnements et avis : vos clients voient un coach qui pense à eux, et votre planning se remplit.</p>")),
        ],
        faq=[
            ("Ça marche avec mon planning actuel ?", "Oui : on se branche sur vos outils (planning, caisse, réseaux). Rien ne change pour votre façon de coacher."),
            ("Les rappels de reprise ne sont pas intrusifs ?", "Un message bienveillant « on vous attend à la séance de mardi ? » est perçu comme de l'attention, pas du spam."),
            ("Par quoi commencer ?", "Les rappels de séance : ils réduisent les no-show et remplissent les créneaux dès la première semaine."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("automatisation-salle-de-sport.html", "Salle de sport"), ("prise-rendez-vous.html", "Prise de RDV"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-bar.html",
        title="Automatisation bar et café : caisse, fournisseurs, événements : le comptoir rentable",
        meta="Rapprochement caisse, commandes fournisseurs, événements, avis : comment un bar automatise sa gestion. Exemples concrets.",
        h1="Bar : <em>la marge derrière le comptoir.</em>",
        sub="Fin de service, inventaire, fournisseurs, événements : chaque soirée génère sa paperasse. Voici comment l'automatisation la fait disparaître.",
        sections=[
            section("Le quotidien du bar", "Les frustrations qui rongent la marge",
                pains([
                    ("Le point de caisse", "CB, espèces, tickets", "Des heures de pointage", "Rapprochement automatique caisse/ventes"),
                    ("Les commandes fournisseurs", "Bières, softs, snacks", "Des ruptures", "Alerte de seuil + commande suggérée"),
                    ("Les avis Google", "La réputation locale", "Des clients satisfaits silencieux", "Demande d'avis après la soirée"),
                ])),
            section("Les 8 tâches à automatiser", "De l'ouverture à la fermeture",
                pains([
                    ("Rapprochement de caisse", "CB, espèces, tickets", "Des heures de pointage", "Rapprochement automatique + écarts signalés"),
                    ("Commandes fournisseurs", "Bières, softs, snacks", "Des ruptures", "Alerte de seuil + commande suggérée"),
                    ("Inventaire", "Kegs, bouteilles, stocks", "Des écarts", "Inventaire simplifié + valorisation automatique"),
                    ("Événements / concerts", "Annonces, rappels", "Des soirées vides", "Annonce automatique + rappels aux habitués"),
                    ("Demande d'avis après la soirée", "Les clients sont contents", "Des avis jamais écrits", "SMS post-soirée → avis Google"),
                    ("Le standard / questions", "Horaires, événements, réservations", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Relance des impayés (pros)", "Événements, traiteurs", "Trésorerie tendue", "Relance polie en 3 paliers"),
                    ("La gestion des stocks", "Boissons, consommables", "Des ruptures en plein service", "Alerte de seuil + commande suggérée"),
                ])),
            section("Votre crainte, honnêtement", "« Un bar, c'est du contact et de l'ambiance. »",
                prose("<p>Et c'est vrai : <strong>l'accueil et l'ambiance restent 100 % humains</strong>. L'automatisation s'occupe de la caisse, des stocks, des fournisseurs et des avis : le patron garde ses soirées pour ses clients, pas pour ses tableaux.</p>")),
        ],
        faq=[
            ("Ça marche avec ma caisse ?", "Oui : on se branche sur vos exports de caisse et vos outils. Le rapprochement vérifie chaque fin de service."),
            ("Les commandes automatiques sont-elles fiables ?", "Elles sont suggérées à partir de vos ventes réelles et vous validez avant envoi au fournisseur."),
            ("Par quoi commencer ?", "Le rapprochement de caisse : c'est le poste qui libère le plus de temps chaque soir."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("automatisation-restauration.html", "Restaurant / traiteur"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-agence-voyage.html",
        title="Automatisation agence de voyage : devis, rappels, avis : le conseiller qui répond vite",
        meta="Devis voyage, rappels de départ, demandes d'avis, suivi clients : comment une agence de voyage automatise. Exemples concrets.",
        h1="Agence de voyage : <em>répondre vite, encaisser vite, faire rêver.</em>",
        sub="Chaque demande = un devis, chaque départ = des rappels, chaque retour = un avis. Voici comment l'automatisation rend l'agence réactive à l'échelle.",
        sections=[
            section("Le quotidien de l'agence", "Les frustrations qui font perdre des ventes",
                pains([
                    ("Les devis lents", "Des demandes multiples", "Des clients qui partent ailleurs", "Devis chiffré en 30 secondes avec votre grille"),
                    ("Les rappels de départ", "Documents, horaires", "Des oublis", "Rappel automatique J-7 et J-1 avec checklist"),
                    ("Les avis", "La réputation fait vendre", "Des clients satisfaits silencieux", "Demande d'avis après le retour"),
                ])),
            section("Les 8 tâches à automatiser", "De la demande au retour de vacances",
                pains([
                    ("Devis express", "Demandes téléphone/email/WhatsApp", "Des réponses lentes", "Devis chiffré en 30 secondes avec la grille"),
                    ("Prise de RDV conseil", "Allers-retours pour caler", "Des clients perdus", "Créneaux proposés + confirmation automatique"),
                    ("Rappels de départ", "Documents, horaires, bagages", "Des oublis", "Rappel J-7 et J-1 avec checklist"),
                    ("Relance des réservations", "Acomptes, soldes", "De l'argent en attente", "Relance polie et automatique"),
                    ("Demande d'avis après le retour", "Le client est conquis", "Des avis jamais écrits", "SMS post-retour → avis Google"),
                    ("Le standard / questions", "Destinations, visas, assurances", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Suivi des clients réguliers", "Anniversaires, envies", "Des clients oubliés", "Message personnalisé de reprise de contact"),
                    ("Comptes-rendus d'entretien conseil", "Envies, budgets, contraintes", "Des heures de rédaction", "CR structuré généré puis validé"),
                ])),
            section("Votre crainte, honnêtement", "« Le voyage se vend sur le rêve et la relation. »",
                prose("<p>Et c'est vrai : <strong>le conseil et le rêve restent 100 % humains</strong>. L'automatisation s'occupe des devis, rappels, relances et avis : vos clients voient une agence qui pense à eux avant, pendant et après. C'est ce qui transforme un voyageur en habitué.</p>")),
        ],
        faq=[
            ("Ça marche avec mon logiciel de réservation ?", "Oui : on se branche sur vos outils (GDS, réservations, facturation). Rien ne change pour votre équipe."),
            ("Les devis automatiques sont-ils personnalisables ?", "Ils suivent votre grille et vos fournisseurs, et vous validez avant envoi."),
            ("Par quoi commencer ?", "Les rappels de départ : c'est le poste qui crée le plus de valeur perçue pour vos clients."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("automatisation-services-b2b.html", "Cabinets et agences"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-dentiste.html",
        title="Automatisation cabinet dentaire : rappels, contrôles, liste d'attente : des dents suivies",
        meta="Rappels de contrôle, prises de RDV, liste d'attente, avis : comment un cabinet dentaire remplit son agenda. Exemples concrets.",
        h1="Cabinet dentaire : <em>des contrôles rappelés, des agendas remplis.</em>",
        sub="Chaque contrôle oublié est un soin retardé et un créneau perdu. Voici comment l'automatisation remplit votre agenda : au service des patients.",
        sections=[
            section("Le quotidien du cabinet", "Les frustrations qui vident l'agenda",
                pains([
                    ("Les contrôles oubliés", "6 mois, 1 an : les échéances", "Des soins retardés", "Rappel automatique au bon moment"),
                    ("Les rendez-vous manqués", "Un créneau perdu", "Des heures non facturées", "Rappel la veille + liste d'attente"),
                    ("Les avis Google", "La réputation locale", "Des patients satisfaits silencieux", "Demande d'avis après le soin"),
                ])),
            section("Les 8 tâches à automatiser", "Du rappel de contrôle au suivi",
                pains([
                    ("Rappels de contrôle", "Échéances 6 mois / 1 an", "Des soins retardés", "Rappel automatique + créneau proposé"),
                    ("Prise de RDV + rappels", "Téléphone, messages", "Des créneaux perdus", "Créneaux proposés, confirmation, rappel J-1"),
                    ("Liste d'attente intelligente", "Une annulation", "Un créneau vide", "Le prochain patient prévenu automatiquement"),
                    ("Demande d'avis après le soin", "Le patient repart satisfait", "Des avis jamais écrits", "SMS post-soin → avis Google"),
                    ("Suivi post-opératoire", "Extractions, implants", "Des suivis oubliés", "Message automatique de suivi + relais si problème"),
                    ("Le standard / questions", "Urgences, devis, horaires", "Des interruptions", "Réponses immédiates, les urgences au cabinet"),
                    ("Relance des devis", "Devis de soins", "Des soins reportés", "Relance polie J+7"),
                    ("Relance des paiements", "Restes à charge", "Des impayés", "Relance polie en 3 paliers"),
                ])),
            section("Votre crainte, honnêtement", "« La santé dentaire, c'est de la relation de confiance. »",
                prose("<p>Et elle le reste : <strong>le soin et la relation restent 100 % humains</strong>. L'automatisation s'occupe des rappels, créneaux et avis : les patients voient un cabinet qui pense à eux. C'est ce qui fait revenir, et recommander.</p>")),
        ],
        faq=[
            ("Les rappels sont personnalisables par patient ?", "Oui : chaque patient a son échéance de contrôle. Le message cite son nom et le motif du rendez-vous."),
            ("Ça marche avec mon logiciel dentaire ?", "Oui : on se branche sur vos outils (planning, dossier patient, facturation). Rien ne change pour votre équipe."),
            ("Par quoi commencer ?", "Les rappels de contrôle : c'est le poste qui remplit l'agenda avec les patients existants."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("automatisation-cabinet-medical.html", "Cabinet médical"), ("prise-rendez-vous.html", "Prise de RDV"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-boulangerie.html",
        title="Automatisation boulangerie : fournisseurs, stocks, avis : la baguette sans paperasse",
        meta="Commandes fournisseurs, stocks, avis, gestion des invendus : comment une boulangerie automatise sa gestion. Exemples concrets.",
        h1="Boulangerie : <em>le four qui chauffe, la paperasse qui disparaît.</em>",
        sub="Farine, fournisseurs, stocks, invendus, avis : chaque jour génère sa paperasse. Voici comment l'automatisation la fait disparaître.",
        sections=[
            section("Le quotidien de la boulangerie", "Les frustrations qui rongent la marge",
                pains([
                    ("Les commandes fournisseurs", "Farine, beurre, emballages", "Des ruptures ou des surstocks", "Commande suggérée d'après les ventes réelles"),
                    ("Les stocks", "Des dizaines de références", "Des écarts", "Inventaire simplifié + alertes de seuil"),
                    ("Les avis Google", "La réputation locale", "Des clients satisfaits silencieux", "Demande d'avis après le passage"),
                ])),
            section("Les 8 tâches à automatiser", "De la commande fournisseur à l'avis",
                pains([
                    ("Commandes fournisseurs", "Farine, beurre, emballages", "Des ruptures", "Commande suggérée d'après les ventes réelles"),
                    ("Gestion des stocks", "Références, seuils", "Des écarts", "Inventaire simplifié + alertes"),
                    ("Gestion des invendus", "Pain, viennoiseries", "Du gaspillage", "Prévision simple d'après les ventes + don suggéré"),
                    ("Devis traiteurs / pros", "Entreprises, événements", "Des réponses lentes", "Devis chiffré en 30 secondes"),
                    ("Demande d'avis après le passage", "Le client est content", "Des avis jamais écrits", "SMS → avis Google"),
                    ("Le standard / questions", "Horaires, commandes, allergènes", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Relance des impayés (pros)", "Traiteurs, entreprises", "Trésorerie tendue", "Relance polie en 3 paliers"),
                    ("La caisse et le rapprochement", "Fin de service, CB, espèces", "Des heures de pointage", "Rapprochement automatique"),
                ])),
            section("Votre crainte, honnêtement", "« Ma boulangerie, c'est du fait main et du contact. »",
                prose("<p>Et c'est vrai : <strong>le pain et l'accueil restent 100 % faits main</strong>. L'automatisation s'occupe des commandes, stocks, invendus et avis : le boulanger retrouve ses nuits, et les clients leur baguette.</p>")),
        ],
        faq=[
            ("Ça marche avec ma caisse ?", "Oui : on se branche sur vos exports de caisse et vos outils. Les suggestions viennent de vos ventes réelles."),
            ("La prévision des invendus est-elle fiable ?", "Elle se base sur vos ventes passées et s'améliore chaque semaine. Vous restez seul juge des quantités."),
            ("Par quoi commencer ?", "La demande d'avis : c'est le poste qui construit votre réputation locale en continu."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("automatisation-restauration.html", "Restaurant / traiteur"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-librairie.html",
        title="Automatisation librairie : commandes, avis, événements : le libraire qui vend plus",
        meta="Commandes clients, avis, événements, stocks : comment une librairie automatise sa gestion. Exemples concrets.",
        h1="Librairie : <em>des commandes suivies, des lecteurs fidèles.</em>",
        sub="Chaque commande, chaque événement, chaque avis compte. Voici comment l'automatisation libère le libraire pour ce qui compte : les livres et les lecteurs.",
        sections=[
            section("Le quotidien de la librairie", "Les frustrations qui grignotent le temps",
                pains([
                    ("Les commandes", "Commandes clients, retours", "Des oublis", "Suivi automatique des commandes + alertes"),
                    ("Les événements", "Dédicaces, ateliers", "Des salles vides", "Annonce automatique + rappels aux habitués"),
                    ("Les avis", "La réputation locale", "Des lecteurs silencieux", "Demande d'avis après l'achat"),
                ])),
            section("Les 8 tâches à automatiser", "De la commande au lecteur fidèle",
                pains([
                    ("Commandes clients", "Arrivages, retours", "Des oublis", "Suivi automatique + notification d'arrivée"),
                    ("Notification d'arrivée", "Le livre est disponible", "Le client oublie de venir", "SMS/email « votre livre est arrivé »"),
                    ("Événements / dédicaces", "Annonces, inscriptions", "Des salles vides", "Annonce automatique + rappels"),
                    ("Demande d'avis après l'achat", "Le lecteur est satisfait", "Des avis jamais écrits", "SMS → avis Google"),
                    ("Commandes fournisseurs", "Stocks, nouveautés", "Des ruptures", "Commande suggérée d'après les ventes"),
                    ("Le standard / questions", "Horaires, disponibilités", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Relance des impayés (pros)", "Écoles, collectivités", "Trésorerie tendue", "Relance polie en 3 paliers"),
                    ("La caisse et le rapprochement", "Fin de service", "Des heures de pointage", "Rapprochement automatique"),
                ])),
            section("Votre crainte, honnêtement", "« La librairie, c'est du conseil, pas des robots. »",
                prose("<p>Et c'est exactement le principe : <strong>le conseil littéraire reste 100 % humain</strong>. L'automatisation s'occupe des commandes, événements, avis et stocks : le libraire passe ses journées à conseiller, pas à saisir.</p>")),
        ],
        faq=[
            ("Ça marche avec mon logiciel de librairie ?", "Oui : on se branche sur vos outils (gestion, caisse, diffusion). Rien ne change pour votre équipe."),
            ("Les notifications d'arrivée marchent ?", "Oui : c'est le poste qui fait revenir les clients et accélère la rotation des commandes."),
            ("Par quoi commencer ?", "La notification d'arrivée : vos clients attendent leurs livres, dites-leur qu'ils sont là."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("hub-commerce-services.html", "Réservoir Commerce"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-psychologue.html",
        title="Automatisation cabinet de psychologue : rendez-vous, rappels, suivi : l'agenda qui s'occupe de tout",
        meta="Rendez-vous, rappels de séance, suivi, avis : comment un psychologue libère son temps pour ses patients. Exemples concrets.",
        h1="Psychologue : <em>l'agenda s'occupe de tout, vous vous occupez des patients.</em>",
        sub="Chaque séance = un rappel, un créneau, parfois un report. L'administratif d'un cabinet libéral est invisible mais lourd. Voici comment l'automatisation l'allège.",
        sections=[
            section("Le quotidien du cabinet", "Les frustrations qui s'ajoutent à la charge",
                pains([
                    ("Les rappels de séance", "No-show, oublis", "Des créneaux perdus", "Rappel automatique la veille + confirmation"),
                    ("Les reports", "Un patient qui décale", "Des trous dans l'agenda", "Report simple + créneau proposé automatiquement"),
                    ("Les avis Google", "La réputation locale", "Des patients satisfaits silencieux", "Demande d'avis (délicate, optionnelle)"),
                ])),
            section("Les 8 tâches à automatiser", "Du premier contact au suivi",
                pains([
                    ("Prise de RDV + rappels", "Premiers contacts, séances", "Des allers-retours", "Créneaux proposés + rappel J-1"),
                    ("Liste d'attente", "Des demandes en attente", "Des places perdues", "Le prochain patient prévenu automatiquement"),
                    ("Gestion des reports", "Annulations, décalages", "Des trous dans l'agenda", "Report simple + créneau proposé"),
                    ("Relance des honoraires", "Séances, forfaits", "Des impayés", "Relance polie et discrète en 3 paliers"),
                    ("Comptes-rendus de séance (notes)", "Notes personnelles", "Des heures de rédaction", "Notes structurées générées puis validées"),
                    ("Le standard / questions", "Horaires, tarifs, démarrage", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Les avis Google", "La réputation", "Des patients silencieux", "Demande discrète et optionnelle"),
                    ("Les rappels de suivi", "Patients en pause", "Des ruptures de suivi", "Message bienveillant de reprise (optionnel)"),
                ])),
            section("Votre crainte, honnêtement", "« La psychothérapie, c'est de l'humain, pas des robots. »",
                prose("<p>Et c'est exactement le principe : <strong>la thérapie reste 100 % humaine et confidentielle</strong>. L'automatisation s'occupe de l'agenda, des rappels et de la discrétion administrative : le patient voit un praticien organisé qui ne le fait jamais attendre.</p>")),
        ],
        faq=[
            ("La confidentialité est-elle garantie ?", "Oui : les données restent dans vos outils, rien n'est envoyé hors de votre système. Les messages sont sobres et neutres."),
            ("Ça marche avec mon agenda actuel ?", "Oui : on se branche sur vos outils (agenda, facturation). Rien ne change pour votre pratique."),
            ("Par quoi commencer ?", "Les rappels de séance : ils réduisent les no-show, sensibles dans cette profession."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("automatisation-cabinet-medical.html", "Cabinet médical"), ("prise-rendez-vous.html", "Prise de RDV"), ("index.html", "← Retour à l'accueil")],
    ),
    dict(
        file="automatisation-aide-domicile.html",
        title="Automatisation services à la personne : planning, facturation, rappels : l'aide qui arrive à l'heure",
        meta="Planning des intervenants, facturation, rappels, CESU : comment une entreprise de services à la personne automatise. Exemples concrets.",
        h1="Services à la personne : <em>des intervenants à l'heure, des clients suivis.</em>",
        sub="Planning, remplacements, facturation CESU, rappels : chaque intervenant, chaque client génère sa coordination. Voici comment l'automatisation la fluidifie.",
        sections=[
            section("Le quotidien de l'entreprise", "Les frustrations qui épuisent la coordination",
                pains([
                    ("Le planning des intervenants", "Remplacements, absences", "Des heures de téléphone", "Planning centralisé + remplacement proposé automatiquement"),
                    ("La facturation CESU", "Heures réelles, tiers payant", "Des erreurs", "Facture générée depuis les interventions réelles"),
                    ("Les clients oubliés", "Aides, courses, RDV", "Des rendez-vous manqués", "Rappel automatique au client et à l'intervenant"),
                ])),
            section("Les 8 tâches à automatiser", "De la prise en charge au suivi",
                pains([
                    ("Planning des intervenants", "Tournées, remplacements", "Des heures de téléphone", "Planning centralisé + alertes d'absence"),
                    ("Gestion des remplacements", "Un intervenant absent", "Un client sans aide", "Remplacement proposé automatiquement"),
                    ("Rappels au client et à l'intervenant", "Interventions à venir", "Des rendez-vous manqués", "Rappel automatique la veille"),
                    ("Facturation des heures réelles", "Heures, déplacements, CESU", "Des erreurs", "Facture générée depuis les interventions"),
                    ("Relance des impayés", "Particuliers, mandataires", "Trésorerie tendue", "Relance polie en 3 paliers"),
                    ("Le standard / questions", "Disponibilités, tarifs, aides", "Des interruptions", "Réponses immédiates, les cas réels à vous"),
                    ("Les avis Google", "La réputation locale", "Des familles satisfaites silencieuses", "Demande d'avis (avec discrétion)"),
                    ("Le suivi des contrats", "Renouvellements, avenants", "Des oublis", "Rappel automatique des échéances"),
                ])),
            section("Votre crainte, honnêtement", "« Les services à la personne, c'est de l'humain avant tout. »",
                prose("<p>Et c'est vrai : <strong>l'aide apportée reste 100 % humaine</strong>. L'automatisation s'occupe de la coordination, des rappels et de la facturation : les familles voient une entreprise fiable qui arrive à l'heure, et votre équipe arrête de courir après le téléphone.</p>")),
        ],
        faq=[
            ("Ça marche avec mon logiciel de SAP ?", "Oui : on se branche sur vos outils (planning, facturation, CESU). Rien ne change pour vos intervenants."),
            ("La facturation CESU est-elle gérée ?", "Oui : elle suit vos conventions et les heures réelles, avec les mentions obligatoires. Vous validez avant envoi."),
            ("Par quoi commencer ?", "Les rappels au client et à l'intervenant : c'est le poste qui réduit immédiatement les rendez-vous manqués."),
            ("Combien ça coûte ?", "Offre découverte 490 € pour une première automatisation en 7 jours, puis maintenance à partir de 149 €/mois."),
        ],
        nav_links=[("hub-sante-bien-etre.html", "Réservoir Santé"), ("index.html", "← Retour à l'accueil")],
    ),
]'''

src = open("build_site.py", encoding="utf-8").read()
marker = "]\n\ndef main():"
assert src.count(marker) == 1, f"marker count = {src.count(marker)}"
src = src.replace(marker, NEW_PAGES + "\n" + marker)
open("build_site.py", "w", encoding="utf-8").write(src)
print("OK : 9 pages ajoutées")
